apiVersion: 1

datasources:
  - name: Parki MySQL
    type: mysql
    uid: parki_mysql
    access: proxy
    url: ${BI_MYSQL_HOST}:${BI_MYSQL_PORT}
    database: ${BI_MYSQL_DATABASE}
    user: ${BI_MYSQL_USER}
    secureJsonData:
      password: ${BI_MYSQL_PASSWORD}
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      timezone: "UTC"
    isDefault: true
    editable: true
